package com.example.boot_self_wt.domain.dao;

import com.example.boot_self_wt.domain.entity.Client;
import tk.mybatis.mapper.common.Mapper;

import java.util.List;

public interface ClientMapper extends Mapper<Client> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client
     *
     * @mbg.generated Wed Sep 12 15:07:39 CST 2018
     */
    int insert(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client
     *
     * @mbg.generated Wed Sep 12 15:07:39 CST 2018
     */
    List<Client> selectAll();

    List<String> selectAllowedClient(String serviceId);

    List<Client> selectAuthorityServiceInfo(int clientId);
}