package com.example.boot_self_wt.domain.dao;

import com.example.boot_self_wt.domain.entity.Login;
import java.util.List;

public interface LoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    int insert(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    Login selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    List<Login> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    int updateByPrimaryKey(Login record);
}