server:
  port: 8081
 
spring:
  datasource:
    name: boot_self_wt
    url: jdbc:mysql://127.0.0.1:3306/spring-boot-activiti?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/example/boot_self_wt/mapper/*Mapper.xml
  type-aliases-package: com.example.boot_self_wt.entity

jwt:
  token-header: Authorization
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45

client:
  id: hr-auth-server
  secret: 123456
  token-header: x-client-token
  expire: 14400
  rsa-secret: x2318^^(*WRYQWR(QW&T
