package com.example.boot_self_wt.domain.entity;

public class Login {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.id
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.user_id
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.login_name
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.password
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.name
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.group
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    private String group;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.id
     *
     * @return the value of login.id
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.id
     *
     * @param id the value for login.id
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.user_id
     *
     * @return the value of login.user_id
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.user_id
     *
     * @param userId the value for login.user_id
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.login_name
     *
     * @return the value of login.login_name
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.login_name
     *
     * @param loginName the value for login.login_name
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.password
     *
     * @return the value of login.password
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.password
     *
     * @param password the value for login.password
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.name
     *
     * @return the value of login.name
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.name
     *
     * @param name the value for login.name
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.group
     *
     * @return the value of login.group
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    public String getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.group
     *
     * @param group the value for login.group
     *
     * @mbg.generated Tue Sep 11 16:41:49 CST 2018
     */
    public void setGroup(String group) {
        this.group = group;
    }
}